<script setup lang="ts">
import { ArrowLeft } from '@lucide/vue'
import { CONSENT_VERSION } from '#shared/raffle'
const config = useRuntimeConfig()
useSeoMeta({ title: 'Privacidade · Sorteio REB' })
</script>
<template>
  <main class="legal-page"><NuxtLink class="back-link" to="/"><ArrowLeft :size="17" /> Voltar ao sorteio</NuxtLink><BrandMark /><p class="eyebrow">SORTEIO DE LIVROS · REB</p><h1>Política de<br><em>privacidade.</em></h1><p class="legal-lead">Veja quais dados coletamos, como usamos e como solicitar sua exclusão.</p>
    <section><h2>Quem cuida dos dados</h2><p>{{ config.public.organizerName }}<template v-if="config.public.organizerCnpj">, CNPJ {{ config.public.organizerCnpj }}</template>, organizadora do sorteio da 2ª Conferência Teológica de 3 de outubro de 2026, é a responsável pelas finalidades do tratamento. Contato: <a :href="`mailto:${config.public.privacyEmail}`">{{ config.public.privacyEmail }}</a>.</p></section>
    <section><h2>O que coletamos e para quê</h2><p>Nome completo, WhatsApp e e-mail são usados para registrar sua participação, evitar inscrições duplicadas, realizar o sorteio e contatar os ganhadores. Registramos a data, a versão do consentimento e os resultados para comprovar o procedimento.</p><p>Seu primeiro nome poderá aparecer entre os nomes da animação durante a transmissão. Se você ganhar, seu nome completo será anunciado. E-mail e WhatsApp não serão exibidos na tela de sorteio.</p><p>Não solicitamos religião, filiação religiosa ou dados de documentos. A participação em uma conferência teológica pode permitir inferências sobre interesses religiosos; por isso, seu consentimento é específico para as finalidades descritas aqui. A participação não declara sua religião.</p></section>
    <section><h2>Sua escolha e o consentimento</h2><p>O tratamento dos dados de inscrição se baseia no consentimento específico do participante (arts. 7º, I, e, quando aplicável, 11, I, da LGPD). Você decide participar e marca o consentimento antes de enviar o formulário. Você pode revogá-lo a qualquer momento pelo contato acima. Antes do sorteio, a retirada dos dados implica sair da lista de participantes.</p><p>Não usaremos sua inscrição para marketing, listas de divulgação ou outros eventos. A participação não exige seguir perfis, comprar, pagar ou fazer doações.</p></section>
    <section><h2>Compartilhamento e entrega</h2><p>Somente os dados dos ganhadores dos três livros necessários ao envio serão compartilhados com a Thomas Nelson Brasil. A REB é responsável pela entrega do Kit Anglicano e não compartilha os dados desse ganhador com a editora. O endereço de entrega será solicitado aos ganhadores em contato privado; ele não é coletado nesta página.</p><p>A hospedagem e o banco de dados (Railway) e a proteção contra robôs (Cloudflare Turnstile) podem tratar dados técnicos para fornecer a infraestrutura. Conforme a região e a contratação escolhidas pela REB, poderá haver processamento fora do Brasil. A REB deve configurar os contratos, a região e os mecanismos de transferência aplicáveis.</p></section>
    <section><h2>Prazo de guarda</h2><p>A proposta de retenção para este sorteio é de até 90 dias após a conferência, para contato, entrega e esclarecimento de dúvidas. Ao final, a REB elimina ou anonimiza os dados, ressalvadas obrigações legais ou a necessidade fundamentada de exercer direitos. O organizador deve executar a limpeza do banco e considerar os prazos de retenção dos backups contratados.</p></section>
    <section><h2>Segurança e cookies</h2><p>O formulário usa validação, proteção contra robôs e limite de tentativas. O acesso administrativo é restrito. Para limitar abuso, armazenamos temporariamente uma representação protegida do endereço IP, sem guardar o IP na inscrição.</p><p>Um registro local no seu navegador evita que o formulário apareça novamente após o envio. O administrador usa um cookie de sessão necessário para autenticação. Não usamos cookies de publicidade ou ferramentas de análise de audiência nesta página. O Turnstile processa sinais técnicos de segurança conforme a <a href="https://www.cloudflare.com/privacypolicy/" target="_blank" rel="noopener noreferrer">política da Cloudflare</a>.</p></section>
    <section><h2>Seus direitos</h2><p>Você pode pedir confirmação de tratamento, acesso, correção, informações sobre compartilhamento, eliminação, portabilidade quando aplicável e revogação do consentimento. Escreva para <a :href="`mailto:${config.public.privacyEmail}`">{{ config.public.privacyEmail }}</a>. Para proteger seus dados, poderemos confirmar sua identidade antes de atender à solicitação.</p></section>
    <p class="legal-version">Versão {{ CONSENT_VERSION }} · Documento operacional sujeito à revisão da organização antes da publicação.</p>
  </main>
</template>
