<script setup lang="ts">
import { ArrowLeft } from '@lucide/vue'
import { prizes, CONSENT_VERSION } from '#shared/raffle'
const config = useRuntimeConfig()
useSeoMeta({ title: 'Regulamento · Sorteio REB' })
</script>
<template>
  <main class="legal-page"><NuxtLink class="back-link" to="/"><ArrowLeft :size="17" /> Voltar ao sorteio</NuxtLink><BrandMark /><p class="eyebrow">2ª CONFERÊNCIA TEOLÓGICA · REB</p><h1>Regulamento<br><em>do sorteio.</em></h1><p class="legal-lead">Três livros e um Kit Anglicano, para quatro pessoas diferentes. Participação gratuita na 2ª Conferência Teológica da REB.</p>
    <section><h2>Organização e participação</h2><p>O sorteio é organizado por {{ config.public.organizerName }}<template v-if="config.public.organizerCnpj">, CNPJ {{ config.public.organizerCnpj }}</template>, com apoio da Thomas Nelson Brasil, durante a conferência online de 3 de outubro de 2026, das 8h às 12h, horário de Brasília.</p><p>Podem participar pessoas com 18 anos ou mais residentes no Brasil. A inscrição é gratuita, sem compra, pagamento ou doação. O link será divulgado durante a transmissão.</p></section>
    <section><h2>Inscrição</h2><p>Preencha nome completo, WhatsApp com DDD e e-mail válidos, confirme sua elegibilidade e manifeste o consentimento. É permitida uma inscrição por participante; e-mail ou WhatsApp repetidos não criam novas chances. Endereços equivalentes do Gmail são tratados como um único e-mail.</p><p>A organização abre e encerra as inscrições manualmente no painel durante a transmissão. Inscrições recebidas após o encerramento não participam. O participante é responsável pela veracidade e pela disponibilidade dos contatos informados.</p></section>
    <section><h2>Prêmios e ordem dos sorteios</h2><p>Serão realizadas quatro rodadas, na ordem abaixo. Cada ganhador recebe o prêmio da sua rodada e é retirado dos sorteios seguintes. O kit é um único prêmio, com todos os seus itens para a mesma pessoa.</p><ol><li v-for="prize in prizes" :key="prize.id"><strong>{{ prize.title }}</strong><template v-if="prize.kind === 'book'"> — {{ prize.author }}. Um exemplar.</template><template v-else>: o livro O Caminho Anglicano, de Thomas McKenzie, uma caneca com a arte “Seja anglicano gostoso demais” e um item surpresa. O livro embrulhado na imagem é apenas uma representação do item surpresa.</template></li></ol></section>
    <section><h2>Como funciona o sorteio</h2><p>Após o encerramento das inscrições, o sistema seleciona uma pessoa por vez de forma aleatória entre os participantes ainda não contemplados. Cada participante elegível tem a mesma probabilidade em cada rodada. O resultado é salvo antes da animação de apresentação, que não interfere na escolha. Os primeiros nomes exibidos na animação são uma amostra visual e não representam a ordem ou a chance de ganhar.</p><p>O primeiro nome dos participantes poderá aparecer na animação; o nome completo do ganhador é anunciado na live. Seus contatos permanecem restritos ao painel administrativo. O sistema não condiciona o recebimento a uma resposta imediata no chat da transmissão.</p></section>
    <section><h2>Contato e envio</h2><p>A REB contatará os quatro ganhadores por WhatsApp ou e-mail para confirmar os dados necessários à entrega. A Thomas Nelson Brasil envia os livros das três primeiras rodadas; a REB envia o Kit Anglicano da quarta rodada. O endereço será informado em contato privado. Somente os dados necessários à entrega dos três livros serão compartilhados com a editora, mediante o consentimento indicado no formulário.</p><p>Os detalhes de prazo e modalidade de envio serão informados ao ganhador pelo responsável pela entrega. Não serão solicitados senhas, códigos de autenticação ou dados de cartão para receber o prêmio.</p></section>
    <section><h2>Integridade e esclarecimentos</h2><p>Inscrições automatizadas, contatos falsos ou tentativas de obter múltiplas chances violam este regulamento. Casos comprovados devem ser tratados pela organização com registro da decisão e respeito aos participantes. Dúvidas podem ser enviadas para <a :href="`mailto:${config.public.privacyEmail}`">{{ config.public.privacyEmail }}</a>.</p><p>O uso dos dados pessoais está detalhado na <NuxtLink to="/privacidade">política de privacidade</NuxtLink>.</p></section>
    <p class="legal-version">Versão {{ CONSENT_VERSION }} · A organização deve revisar as regras e o enquadramento jurídico antes de publicar. Este documento não declara autorização ou dispensa legal para a distribuição de prêmios.</p>
  </main>
</template>
